# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-13 20:39
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('widget', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Manuscript',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('doi', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_text', models.CharField(max_length=200)),
                ('help_text', models.TextField()),
                ('category', models.CharField(choices=[('DV', 'Discovery Value'), ('AC', 'Actionability'), ('CR', 'Certitude'), ('EX', 'Expertise')], default='DV', max_length=2)),
                ('question_type', models.CharField(choices=[('SL', 'Slider')], default='SL', max_length=2)),
            ],
        ),
        migrations.CreateModel(
            name='Rating',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.FloatField()),
                ('create_date', models.DateTimeField(auto_now_add=True)),
                ('modify_date', models.DateTimeField(auto_now=True)),
                ('manuscript', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='discovery.Manuscript')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='discovery.Question')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('version', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='widget.Version')),
            ],
        ),
    ]
