# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-13 20:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Version',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('major', models.PositiveSmallIntegerField(default=0)),
                ('minor', models.PositiveSmallIntegerField(default=0)),
                ('patch', models.PositiveSmallIntegerField(default=0)),
            ],
        ),
    ]
