# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-11-01 20:33
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('widget', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='version',
            unique_together=set([('major', 'minor', 'patch')]),
        ),
    ]
